# Generated by Django 6.0.5 on 2026-05-18 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(db_index=True, unique=True)),
                ('title', models.CharField(blank=True, db_index=True, max_length=200)),
                ('image', models.URLField(blank=True, max_length=500)),
                ('network_technology', models.CharField(blank=True, max_length=100)),
                ('network_2g_bands', models.CharField(blank=True, max_length=200)),
                ('network_3g_bands', models.CharField(blank=True, max_length=200)),
                ('network_4g_bands', models.CharField(blank=True, max_length=500)),
                ('network_5g_bands', models.CharField(blank=True, max_length=500)),
                ('network_speed', models.CharField(blank=True, max_length=100)),
                ('announced', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('dimensions', models.CharField(blank=True, max_length=100)),
                ('weight', models.CharField(blank=True, max_length=50)),
                ('sim', models.CharField(blank=True, max_length=100)),
                ('body_other', models.TextField(blank=True)),
                ('display_type', models.CharField(blank=True, max_length=100)),
                ('display_size', models.CharField(blank=True, max_length=100)),
                ('display_resolution', models.CharField(blank=True, max_length=100)),
                ('display_protection', models.CharField(blank=True, max_length=100)),
                ('os', models.CharField(blank=True, max_length=100)),
                ('chipset', models.CharField(blank=True, max_length=100)),
                ('cpu', models.CharField(blank=True, max_length=200)),
                ('gpu', models.CharField(blank=True, max_length=100)),
                ('card_slot', models.CharField(blank=True, max_length=100)),
                ('internal_memory', models.CharField(blank=True, max_length=100)),
                ('memory_type', models.CharField(blank=True, max_length=50)),
                ('main_camera_modules', models.TextField(blank=True)),
                ('main_camera_features', models.CharField(blank=True, max_length=200)),
                ('main_camera_video', models.CharField(blank=True, max_length=200)),
                ('selfie_camera_modules', models.CharField(blank=True, max_length=200)),
                ('selfie_camera_video', models.CharField(blank=True, max_length=100)),
                ('loudspeaker', models.BooleanField(default=False)),
                ('headphone_jack', models.BooleanField(default=False)),
                ('wlan', models.CharField(blank=True, max_length=100)),
                ('bluetooth', models.CharField(blank=True, max_length=100)),
                ('positioning', models.CharField(blank=True, max_length=200)),
                ('nfc', models.BooleanField(default=False)),
                ('infrared_port', models.BooleanField(default=False)),
                ('radio', models.CharField(blank=True, max_length=100)),
                ('usb', models.CharField(blank=True, max_length=100)),
                ('sensors', models.CharField(blank=True, max_length=300)),
                ('battery_type', models.CharField(blank=True, max_length=100)),
                ('charging', models.TextField(blank=True)),
                ('colors', models.CharField(blank=True, max_length=100)),
                ('price', models.CharField(blank=True, max_length=100)),
                ('eu_energy_class', models.CharField(blank=True, max_length=20)),
                ('eu_battery_endurance', models.CharField(blank=True, max_length=100)),
                ('eu_free_fall_class', models.CharField(blank=True, max_length=100)),
                ('eu_repairability_class', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
