# Generated by Django 6.0.5 on 2026-05-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonespec',
            name='number',
            field=models.IntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='phonespec',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
    ]
